school-many-to-many/config/routes.rb
Rails.application.routes.draw do
  resources :homeworks
  resources :students
end

school-many-to-many/app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :subject
	belongs_to :student

	validates :student, uniqueness: {
		scope: :subject, 
		message: "No puedes repetir materias"
	}


end

school-many-to-many/app/models/homework.rb
class Homework < ActiveRecord::Base
end

school-many-to-many/app/models/student.rb
class Student < ActiveRecord::Base
	has_many :enrollments
	has_many :subjects, through: :enrollments

	validates :name, :code, presence: true
	validates :code, uniqueness: true

end

school-many-to-many/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :enrollments
	has_many :students, through: :enrollments
end

school-many-to-many/app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:name)
    end
end

school-many-to-many/app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all

		@students2 = @students.where("name LIKE ?", "%m%")
		# SELECT * FROM STUDENTS WHERE name LIKE "%m%"
		@students3 = @students.where("name LIKE ?", "%#{params[:name]}%")
		# SELECT * FROM STUDENTS WHERE name = "Marlon"

		# http://localhost:3000/students?name=Juancho&code=COD
		
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			redirect_to students_path, notice: "Se creo correctamente"
		else
			render :new
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		if @student.update_attributes(student_params)
			redirect_to students_path, notice: "Se actualizo correctamente"
		else
			render :edit
		end
	end

	private

	def student_params
		params.require(:student).permit(:name, :code, {subject_ids: []})
	end

end

school-many-to-many/app/helpers/homeworks_helper.rb
module HomeworksHelper
end

school-many-to-many/app/helpers/students_helper.rb
module StudentsHelper
end

school-many-to-many/app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

school-many-to-many/app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

school-many-to-many/app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.name %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

school-many-to-many/app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

school-many-to-many/app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @homework.name %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

school-many-to-many/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolManyToMany</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

school-many-to-many/app/views/students/_form.html.erb
<%= form_for student do |f| %>
	
  <ul>
	  <% student.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	  <% end %>
  </ul>
  
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :code %>
		<%= f.text_field :code %>
	</div>

	<div>
		<%= f.label :subjects %>
		<%= f.collection_check_boxes :subject_ids, Subject.all, :id, :name %>
	</div>


	<div>
		<%= f.submit %>
	</div>

<% end %>

school-many-to-many/app/views/students/edit.html.erb
<h1>Edit Student <%= @student.name %></h1>

<%= render partial: "form", locals: {student: @student } %>

school-many-to-many/app/views/students/index.html.erb
<h1>Students</h1>

<%= link_to "Add student", new_student_path %>

<ul>
	<% @students.each do |student| %>
		<li class="student">
			<span class="student-name"><%= student.name %></span>
		</li>
	<% end %>
</ul>

<h3>Students with M in the name</h3>
<ul>
	<% @students2.each do |student| %>
		<li class="student">
			<span class="student-name"><%= student.name %></span>
		</li>
	<% end %>
</ul>

<h3>Estudiante con parametro dinamico</h3>
<ul>
	<% @students3.each do |student| %>
		<li class="student">
			<span class="student-name"><%= student.name %></span>
		</li>
	<% end %>
</ul>

<%= form_tag "/students", method: :get do |f| %>
	<%= label_tag "Nombre" %>
	<%= text_field_tag :name %>
	<%= submit_tag "Buscar" %>
<% end %>

school-many-to-many/app/views/students/new.html.erb
<h1>Add Student</h1>

<%= render partial: "form", locals: {student: @student } %>