aereolinea/config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :flights
  resources :routes
  resources :pilots
  resources :airplanes
  resources :cities

     get 'flights/:id/buy_ticket/:flight' => 'passengers#buy_ticket', as: "buy_ticket"

end

aereolinea/app/models/passenger.rb
class Passenger < ActiveRecord::Base

	has_and_belongs_to_many :flights

	validates :name, :document, :lastname, presence: true
end

aereolinea/app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy, :buy_ticket]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  def buy_ticket
    @flight= Flight.find(params[:flight])
    @passenger.flights << @flight
    @passenger.save
    redirect_to flights_path, notice: 'Tiquete Comprado' 

  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:name, :document, :lastname)
    end
end

aereolinea/app/helpers/passengers_helper.rb
module PassengersHelper
end

aereolinea/app/views/passengers/_form.html.erb
<%= form_for(@passenger) do |f| %>
  <% if @passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% @passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.text_field :document %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aereolinea/app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form' %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

aereolinea/app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Document</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.document %></td>
        <td><%= passenger.lastname %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

aereolinea/app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form' %>

<%= link_to 'Back', passengers_path %>

aereolinea/app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @passenger.document %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @passenger.lastname %>
</p>

<p>Tickets</p>
<ul>
<% @passenger.flights.each do |f|%>
<li><%= f.route.define_route %> - <%= f.date.strftime("%B %d %Y %H:%M:%S") %></li>
<% end %>
</ul>
<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>