aereolinea/config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :flights
  resources :routes
  resources :pilots
  resources :airplanes
  resources :cities

     get 'flights/:id/buy_ticket/:flight' => 'passengers#buy_ticket', as: "buy_ticket"

end

aereolinea/app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :city_o, class_name: 'City', foreign_key: 'city_o_id' 
  belongs_to :city_d, class_name: 'City', foreign_key: 'city_d_id'

  has_many :flights

  validates  :city_d_id, :city_o_id, presence: true
  validates  :city_d_id, :city_o_id, numericality: {only_integer: true}

  validate :city_o_city_d

   def city_o_city_d
  	errors.add(:city_d_id, "La ciudad destino debe ser diferente a la ciudad origen.") if self.city_d_id == self.city_o_id
   end

   def define_route
   	"#{self.city_o.name} - #{self.city_d.name}"
   end
end

aereolinea/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:city_o_id, :city_d_id)
    end
end

aereolinea/app/helpers/routes_helper.rb
module RoutesHelper
end

aereolinea/app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_o_id %><br>
    <%= f.select :city_o_id, City.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :city_d_id %><br>
    <%= f.select :city_d_id, City.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aereolinea/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

aereolinea/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rutas</h1>

<table>
  <thead>
    <tr>
      <th>Ciudad origen</th>
      <th>Ciudad destino</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.city_o.name %></td>
        <td><%= route.city_d.name %></td>
        <td><%= link_to 'ver ruta', route %></td>
        <td><%= link_to 'editar', edit_route_path(route) %></td>
        <td><%= link_to 'eliminar', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'crear ruta', new_route_path %>

aereolinea/app/views/routes/new.html.erb
<h1>Crear Ruta</h1>

<%= render 'form' %>

<%= link_to 'Atras', routes_path %>

aereolinea/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Ciudad origen:</h2>
  <span><%= @route.city_o.name %></span><br>
  <span>Pais:<%= @route.city_o.country %></span>
</p>

<p>
  <h2>Ciudad destino:</h2>
  <span><%= @route.city_d.name %></span><br>
  <span>Pais:<%= @route.city_d.country %></span>
</p>

<%= link_to 'Editar', edit_route_path(@route) %> |
<%= link_to 'Atras', routes_path %>